/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "interface1.h"


void
gestion_usuarios_1(char *host)
{
	CLIENT *clnt;
	bool_t  *result_1;
	nodo_usuario  registraradministrador_1_arg;
	bool_t  *result_2;
	nodo_usuario  registrarcliente_1_arg;
	bool_t  *result_3;
	nodo_usuario  enviardatossesionadministrador_1_arg;
	bool_t  *result_4;
	nodo_usuario  enviardatossesioncliente_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, gestion_usuarios, gestion_usuarios_version_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = registraradministrador_1(&registraradministrador_1_arg, clnt);
	if (result_1 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = registrarcliente_1(&registrarcliente_1_arg, clnt);
	if (result_2 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = enviardatossesionadministrador_1(&enviardatossesionadministrador_1_arg, clnt);
	if (result_3 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = enviardatossesioncliente_1(&enviardatossesioncliente_1_arg, clnt);
	if (result_4 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	gestion_usuarios_1 (host);
exit (0);
}
