/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "interface2.h"
#include <string.h>

nodo_producto vectorProductos[5];
int posProductoRegistrar=0;

bool_t *
registrarproducto_2_svc(nodo_producto *argp, struct svc_req *rqstp)
{
	static bool_t  result;
	printf("\n Invocando registrar producto");
	printf("\n Codigo del producto %d" ,argp->codigoProducto);
	if(posProductoRegistrar<5){
		vectorProductos[posProductoRegistrar]=*argp;
		printf("\n RESPUESTA DEL SERVIDOR:");
		printf("\n Se registro un producto!");
		printf("\n **************************");
		result=TRUE;
		posProductoRegistrar++;
	}
	else{
		printf("\n RESPUESTA DEL SERVIDOR:");
		printf("\n NO se pudo registrar el producto.");
		printf("\n ************************************");
		return FALSE;
	}
	
	return &result;
}

nodo_producto *
consultarproducto_2_svc(char **argp, struct svc_req *rqstp)
{
	static nodo_producto  result;
	
	printf("\n Invocando a consultarProducto producto");
	for(int i = 0 ; i<posProductoRegistrar ; i++){
		if(strcmp(vectorProductos[i].nombre,*argp) == 0){
			result=vectorProductos[i];
			printf("\n RESPUESTA DEL SERVIDOR:");
			printf("\n Producto encontrado!");
			printf("\n **********************");
			return &result;
		}
	}
	printf("\n RESPUESTA DEL SERVIDOR:");
	printf("\n Producto no encontrado.");
	printf("\n ***********************");
	return &result;
}
