/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _INTERFACE2_H_RPCGEN
#define _INTERFACE2_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNOM 20

struct nodo_producto {
	int codigoProducto;
	char nombre[MAXNOM];
	float valor;
};
typedef struct nodo_producto nodo_producto;

#define gestion_productos 0x20000002
#define gestion_productos_version_1 2

#if defined(__STDC__) || defined(__cplusplus)
#define administradorRegistrarProductoOfertar 1
extern  bool_t * administradorregistrarproductoofertar_2(nodo_producto *, CLIENT *);
extern  bool_t * administradorregistrarproductoofertar_2_svc(nodo_producto *, struct svc_req *);
#define listarProductosOfertarCLiente 2
extern  void * listarproductosofertarcliente_2(void *, CLIENT *);
extern  void * listarproductosofertarcliente_2_svc(void *, struct svc_req *);
#define abrirCerrarSubasta 3
extern  bool_t * abrircerrarsubasta_2(int *, CLIENT *);
extern  bool_t * abrircerrarsubasta_2_svc(int *, struct svc_req *);
#define listarProductosCLiente 4
extern  void * listarproductoscliente_2(void *, CLIENT *);
extern  void * listarproductoscliente_2_svc(void *, struct svc_req *);
#define consultarProducto 5
extern  nodo_producto * consultarproducto_2(char **, CLIENT *);
extern  nodo_producto * consultarproducto_2_svc(char **, struct svc_req *);
#define consultarDatosProductoActualSubastando 6
extern  void * consultardatosproductoactualsubastando_2(void *, CLIENT *);
extern  void * consultardatosproductoactualsubastando_2_svc(void *, struct svc_req *);
#define ofrecerOferta 7
extern  void * ofreceroferta_2(void *, CLIENT *);
extern  void * ofreceroferta_2_svc(void *, struct svc_req *);
extern int gestion_productos_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define administradorRegistrarProductoOfertar 1
extern  bool_t * administradorregistrarproductoofertar_2();
extern  bool_t * administradorregistrarproductoofertar_2_svc();
#define listarProductosOfertarCLiente 2
extern  void * listarproductosofertarcliente_2();
extern  void * listarproductosofertarcliente_2_svc();
#define abrirCerrarSubasta 3
extern  bool_t * abrircerrarsubasta_2();
extern  bool_t * abrircerrarsubasta_2_svc();
#define listarProductosCLiente 4
extern  void * listarproductoscliente_2();
extern  void * listarproductoscliente_2_svc();
#define consultarProducto 5
extern  nodo_producto * consultarproducto_2();
extern  nodo_producto * consultarproducto_2_svc();
#define consultarDatosProductoActualSubastando 6
extern  void * consultardatosproductoactualsubastando_2();
extern  void * consultardatosproductoactualsubastando_2_svc();
#define ofrecerOferta 7
extern  void * ofreceroferta_2();
extern  void * ofreceroferta_2_svc();
extern int gestion_productos_2_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nodo_producto (XDR *, nodo_producto*);

#else /* K&R C */
extern bool_t xdr_nodo_producto ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_INTERFACE2_H_RPCGEN */
