/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "interface1.h"

bool_t
xdr_nodo_usuario (XDR *xdrs, nodo_usuario *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->login, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->contrasenia, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
