/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "interface2.h"


void
gestion_productos_2(char *host)
{
	CLIENT *clnt;
	bool_t  *result_1;
	nodo_producto  registrarproducto_2_arg;
	nodo_producto  *result_2;
	char * consultarproducto_2_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, gestion_productos, gestion_productos_version_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = registrarproducto_2(&registrarproducto_2_arg, clnt);
	if (result_1 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = consultarproducto_2(&consultarproducto_2_arg, clnt);
	if (result_2 == (nodo_producto *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	gestion_productos_2 (host);
exit (0);
}
