/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "interface1.h"
#include "interface2.h"

void menuLogin(){
	printf("\n === bienvenido ===");
	printf("\n 1. Iniciar sesion");
	printf("\n 2. salir");
}
void menuPrincipal(){
	printf("\n === menu ===");
	printf("\n 1. Registrar producto");
	printf("\n 2. Consultar producto");
	printf("\n 3. salir");
}
void
gestion_usuarios_1(char *host)
{
	CLIENT *clnt1;
	bool_t  *result_1;
	nodo_usuario  objUsuario;
	CLIENT *clnt2;
	bool_t  *result_2;
	nodo_producto objProducto;
	nodo_producto *result_consulta;
	char *nombreProductoConsultar;

#ifndef	DEBUG
	clnt1 = clnt_create (host, gestion_usuarios, gestion_usuarios_version_1, "udp");
	if (clnt1 == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
	clnt2 = clnt_create (host, gestion_productos, gestion_productos_version_1, "tcp");
	if (clnt2 == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	int ingresoLogin;
	do{
		menuLogin();
		printf("\n Digite una opcion:");
		scanf("%d",&ingresoLogin);

		if(ingresoLogin == 1){
			printf("\n Ingrese el login:");
			scanf("%s",objUsuario.login);
			printf("\n Ingrese la contrasenia:");
			scanf("%s",objUsuario.contrasenia);

			result_1 = enviardatossesion_1(&objUsuario, clnt1);
			if (result_1 == (bool_t *) NULL) {
				clnt_perror (clnt1, "call failed");
			}

			if(*result_1 == TRUE){
				int opcionMenuProducto;
				do{
					menuPrincipal();
					printf("\n Digite una opcion:");
					scanf("%d",&opcionMenuProducto);

					switch (opcionMenuProducto)
					{
						case 1:
							printf("\n Digite el codigo:");
							scanf("%d",&objProducto.codigoProducto);
							printf("\n Digite el nombre:");
							scanf("%s",objProducto.nombre);
							printf("\n Digite el valor:");
							scanf("%f",&objProducto.valor);

							result_2 = registrarproducto_2(&objProducto, clnt2);
							if (result_2 == (bool_t *) NULL) {
								clnt_perror (clnt2, "call failed");
							}
							else if(*result_2==TRUE){
								printf(" \n Produto registrado correctamente!");
							}
							else{
								printf("\n Error al registrar,se excedio el numero maximo de productos.");
							}
						break;
						case 2:
							nombreProductoConsultar = (char*) malloc(20*sizeof(char));
							printf("\n Digite el nombre:");
							scanf("%s",nombreProductoConsultar);
							result_consulta = consultarproducto_2(&nombreProductoConsultar, clnt2);
							if (result_consulta == (nodo_producto *) NULL) {
								clnt_perror (clnt2, "call failed");
							}
							else if(strcmp(result_consulta->nombre,nombreProductoConsultar) == 0){
								printf("\n Codigo: %d",result_consulta->codigoProducto);
								printf("\n Nombre: %s",result_consulta->nombre);
								printf("\n Valor: %f",result_consulta->valor);
							}
							else{
								printf("\n El producto no fue encontrado!");
							}
						break;
						case 3:
							printf("\n Saliendo...");
						break;
						default:
							printf("\n Digite una opcion valida.");
						break;
					}
				}while(opcionMenuProducto != 3);
			}
			else if(*result_1 == FALSE){
				printf("\n Error, login o contrasenia no valida.");
			}
		}

		if(ingresoLogin!=1 && ingresoLogin!=2){
			printf("\n Error,digite una opcion valida");
		}
	}while(ingresoLogin!=2);
	
#ifndef	DEBUG
	clnt_destroy (clnt1);
	clnt_destroy (clnt2);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	gestion_usuarios_1 (host);
exit (0);
}
