/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _INTERFACE2_H_RPCGEN
#define _INTERFACE2_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNOM 20

struct nodo_producto {
	int codigoProducto;
	char nombre[MAXNOM];
	float valor;
};
typedef struct nodo_producto nodo_producto;

#define gestion_productos 0x20000002
#define gestion_productos_version_1 2

#if defined(__STDC__) || defined(__cplusplus)
#define registrarProducto 1
extern  bool_t * registrarproducto_2(nodo_producto *, CLIENT *);
extern  bool_t * registrarproducto_2_svc(nodo_producto *, struct svc_req *);
#define consultarProducto 2
extern  nodo_producto * consultarproducto_2(char **, CLIENT *);
extern  nodo_producto * consultarproducto_2_svc(char **, struct svc_req *);
extern int gestion_productos_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define registrarProducto 1
extern  bool_t * registrarproducto_2();
extern  bool_t * registrarproducto_2_svc();
#define consultarProducto 2
extern  nodo_producto * consultarproducto_2();
extern  nodo_producto * consultarproducto_2_svc();
extern int gestion_productos_2_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nodo_producto (XDR *, nodo_producto*);

#else /* K&R C */
extern bool_t xdr_nodo_producto ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_INTERFACE2_H_RPCGEN */
